#!/bin/bash

################################### Parametros ############################################### 

# Horas que deberia estar disponibles el servidor [min]
hd=600 

#Establecer la direccion del servidor a testear
servidor="192.168.2.90"

#rutaArchivoDiagnostico
rarch="/home/ubuntu/Desktop"

# Tiempo para realizar el Ping en minutos [min] 
tping=2

# Numeros de paquetes a enviar
numPaquetes=$1
numPaquetes=${numPaquetes:-1}

# Tiempo entre paquetes
tiempoEntrePaquetes=$2
tiempoEntrePaquetes=${tiempoEntrePaquetes:-2}

# Email predeterminado para el envio de la alerta
nombreUsuario="g.apaza007@gmail.com"

# Variables donde se almacena los resultados del comando ping
numeroPaquetesTransmitidos=0
numeroPaquetesRecividos=0
numeroPaquetesPerdidos=0
resultadoPing=""

# Colores
rojo="\e[1;31m"
verde="\e[1;32m"
amarillo="\e[1;33m"
azul="\e[1;34m"
lila="\e[1;35m"
turquesa="\e[1;36m"
cerrarColor="\e[0m"

################################################################################################


# Funcion que envia un correo electronico o sms a una determinado contacto

function alertaCaida()
{
  curl -n --ssl-reqd --mail-from $nombreUsuario --mail-rcpt "hmejia@solucredit.com.bo" --url smtps://smtp.gmail.com:465 --user "$nombreUsuario:$contrasenia" --upload-file $rarch/mail.txt
}

# funcion que captura  la respuesta del comando ping con un envio ICMP
function capturaPing()
{
  ((numPaquetes=$tping*10))
  resultadoPing=$(ping -q -c $numPaquetes $servidor | grep "packets transmitted")
  resultadoPing=${resultadoPing/,\ +*errors,/","}
    #Paquetes transmitidos
    npt=${resultadoPing%,*ved*}
    npt=${npt%\ *packets transmitted}
    npt=$(echo $npt | tr -d '[[:space:]]')
    #Paquetes recividos
    npr=${resultadoPing#*tted,}
    npr=${npr%,\ *loss*}
    npr=${npr%\ *received}
    npr=$(echo $npr | tr -d '[[:space:]]')
    #Paquetes Perdidos
    npp=${resultadoPing#*ved,}
    npp=${npp%,*ms}
    npp=${npp%\%*packet loss}
    npp=$(echo $npp | tr -d '[[:space:]]')

    npt=${npt:-0}
    npr=${npr:-0}
    npp=${npp:-30}

    ((numeroPaquetesTransmitidos=$numeroPaquetesTransmitidos+$npt))
    ((numeroPaquetesRecividos=$numeroPaquetesRecividos+$npr))
    ((numeroPaquetesPerdidos=$numeroPaquetesPerdidos+$npp))

}

# Funcion de llenao de archivo email

function armadoArchivoMail()
{
  echo -e "From: 'George' <g.apaza007@gmail.com>" > $rarch/mail.txt
  echo -e "To: 'Helio' <hmejia@solucredit.com.bo>" >> $rarch/mail.txt
  echo -e "Subject: Alerta-Servidor-En-Riesgo" >> $rarch/mail.txt
  echo -e "\n\n=============== Informacion de estadisticas del servidor ================" >> $rarch/mail.txt
  echo -e "= NUMERO DE PAQUETES TRANSMITIDOS: $numeroPaquetesTransmitidos                                    =" >> $rarch/mail.txt
  echo -e "= NUMERO DE PAQUETES RECIBIDOS: $numeroPaquetesRecividos                                       =" >> $rarch/mail.txt
  echo -e "= PORCENTAJE DE PAQUETES PERDIDOS: $numeroPaquetesPerdidos                                   =" >> $rarch/mail.txt
  echo -e "=========================================================================" >> $rarch/mail.txt
}



# Funcion principal

#function main()
#{ 
  # Tiempo de sondeo en segundos
  ts=5
  contador=0
  while [ $contador -lt 1 ]
  do
    capturaPing
    ((contador=$contador+1))
    sleep $ts
  done
  # datos de la fecha y hora
  fechaHoraInicial=$(date +'%x %X')
  (cat $rarch/diagnostico.txt | grep -w Informacion) 2>/dev/null 1>/dev/null
  if [[ $? == 0 ]]
  then
   echo " " > /dev/null
  else
	echo -e "\n fecha			Informacion" >> ${rarch}/diagnostico.txt 
        echo -e " =====			===========" >> ${rarch}/diagnostico.txt
  fi

   if [[ $numeroPaquetesPerdidos -eq 0 ]]
    then
	echo -e "[++] $fechaHoraInicial	Paquetes Transmitidos: ${numeroPaquetesTransmitidos}, Paquetes Recividos: ${numeroPaquetesRecividos}, Paquetes perdidos: ${numeroPaquetesPerdidos}%" >> ${rarch}/diagnostico.txt
	cat ${rarch}/diagnostico.txt
    else
     if  [[ $numeroPaquetesPerdidos -le 30 && $numeroPaquetesPerdidos -gt 0 ]]
     then
	echo -e "[+-] $fechaHoraInicial	Paquetes Transmitidos: ${numeroPaquetesTransmitidos}, Paquetes Recividos: ${numeroPaquetesRecividos}, Paquetes perdidos: ${numeroPaquetesPerdidos}%" >> ${rarch}/diagnostico.txt
	cat ${rarch}/diagnostico.txt
     else
        armadoArchivoMail
	#alertaCaida
	echo -e "[--] $fechaHoraInicial	Paquetes Transmitidos: ${numeroPaquetesTransmitidos}, Paquetes Recividos: ${numeroPaquetesRecividos}, Paquetes perdidos: ${numeroPaquetesPerdidos}%" >> ${rarch}/diagnostico.txt
	cat ${rarch}/diagnostico.txt
	cat ${rarch}/mail.txt
     fi
   fi
#}
